import "./global.css";
import Link from "next/link";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
        <div className="navbar bg-base-100">
  <div className="flex-1">
    <Link href="/" className="btn btn-ghost text-xl">Wing-On</Link>
  </div>
  <div className="flex-none">
    <ul className="menu menu-horizontal px-1">
      <li><Link href="/login">Login</Link></li>
    </ul>
  </div>
</div>
          </header>
        {children}
        <footer>footer</footer>
        </body>
    </html>
  )
}
